name: Deploy homepage

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install(&setup)
        run: npm install
      
      - name: Test
        run: npm run test
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dists
          path: dist/
  deploy-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup download dists
        run: mkdir dist && cd dist

      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: dists
      - name: Post download dists
        run: cd ..

      - name: publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  deploy-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup download dists
        run: mkdir dist && cd dist

      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: dists
      - name: Post download dists
        run: cd ..
      
      - name: Build homepage
        run: npm run build:homepage
      
      - name: Setup pages
        uses: actions/configure-pages@v5
      
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: './homepage/dist'
      
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
