name: Build homepage and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy style
        run: cp ./homepage/public/style.css ./homepage/dist/style.css

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build:homepage
      
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: './homepage/dist'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
      